Clarify restart messages

diff --git a/nginx/watch-nginx b/nginx/watch-nginx
--- a/nginx/watch-nginx
+++ b/nginx/watch-nginx
@@ -3,7 +3,7 @@
 ( 
     inotifywait -r -m -e modify -e move -e create -e delete /etc/nginx | while read LINE; do
       echo -n "Sending HUP signal to nginx..."
-      killall -HUP nginx && echo "SUCCESS" || echo "FAILED"
+      killall -HUP nginx && echo "NGINX restart: SUCCESS" || echo "NGINX restart: FAILED"
   done	    
 ) &
 
